/* oxlint-disable next/no-html-link-for-pages -- simple internal links work in the Sites runtime */
import { ArrowLeft, BookOpen, Coins, Handshake, Orbit, Shield, Sparkles, Swords } from 'lucide-react';
import type React from 'react';

const steps = [
  ['1', 'Regroup', 'Recover one token from the Warp and place it on one of your home bases. If you have no challenge card, discard your hand and draw a new seven-card hand.'],
  ['2', 'Destiny', 'The destiny draw identifies the color you must encounter. If your own color appears, you may attack another player or attempt to reclaim a home planet.'],
  ['3', 'Launch', 'Choose one planet in the selected system and send one to four tokens through the cone. Macron normally sends only one. Tokens may come from any of your bases.'],
  ['4', 'Alliance', 'The offense and defense may invite the other players. Invited players choose a side and commit up to four tokens. Moon encounters skip alliances.'],
  ['5', 'Planning', 'The two main players secretly choose an Attack or Compromise card. Optional Edicts and Kickers appear in the tactics window.'],
  ['6', 'Reveal', 'Reveal both cards, apply powers and modifiers, compare totals, then move tokens and award rewards. A player normally receives a second challenge after completing the first.'],
];

const aliens = [
  ['Clone', 'Replication', 'Keep every challenge card you play instead of discarding it.'],
  ['Macron', 'Mass', 'Each of your tokens contributes four strength. You normally launch only one token.'],
  ['Virus', 'Multiplication', 'Multiply your Attack card by the number of tokens on your side, including allied tokens.'],
  ['Zombie', 'Immortality', 'Your defeated tokens return to your bases instead of entering the Warp.'],
  ['Anti-Matter', 'Negation', 'When you are a main player, lower attack totals win. Defense still wins ties.'],
  ['Pacifist', 'Peace', 'As a main player, your Compromise defeats an opponent’s Attack.'],
  ['Warpish', 'Necromancy', 'Add the number of your tokens in the Warp to your combat total.'],
  ['Mutant', 'Regeneration', 'After you are a main player, refill your hand to eight cards.'],
];

export default function RulesPage(){return <main className="rules-page">
  <header className="rules-hero"><nav><a href="/"><ArrowLeft/> Return to game</a><span>THE EON YEARS · SOLO EDITION</span></nav><div><p className="eyebrow">FIELD MANUAL 01</p><h1>HOW TO CONQUER<br/><span>THE COSMOS</span></h1><p>Everything you need to play this digital adaptation, from your first destiny draw to a shared victory.</p></div></header>
  <aside className="rules-index"><b><BookOpen/> RULES INDEX</b><a href="#goal">Goal</a><a href="#turn">The turn</a><a href="#combat">Challenges</a><a href="#cards">Cards</a><a href="#powers">Alien powers</a><a href="#expansions">Expansions</a><a href="#solo">Solo adaptations</a></aside>
  <article className="rulebook">
    <section id="goal" className="rules-lead"><p className="eyebrow">THE GREAT OBJECTIVE</p><h2>Build five bases beyond your home system.</h2><p>A base is one or more of your tokens on a planet. Place bases on five different planets belonging to other players and you win immediately. Several players can win together when allies establish their fifth foreign bases in the same encounter.</p><div className="rule-callout"><Orbit/><div><b>YOUR STARTING EMPIRE</b><span>Five home planets · twenty tokens · seven cards · one alien power</span></div></div></section>
    <section id="turn"><p className="eyebrow">ANATOMY OF A TURN</p><h2>Six phases. Endless trouble.</h2><div className="turn-steps">{steps.map(([n,name,text])=><div key={name}><strong>{n}</strong><h3>{name}</h3><p>{text}</p></div>)}</div></section>
    <section id="combat"><p className="eyebrow">RESOLVING A CHALLENGE</p><h2>Attack, negotiate, or betray expectations.</h2><div className="rule-grid"><div><Swords/><h3>Attack vs. Attack</h3><p>Each side totals its revealed Attack card, token strength, allied strength, Lucre spent, Kickers, Moon effects, and alien powers. The larger total wins. The defense wins a tie.</p><p>Winning offensive tokens land on the planet and form bases. Losing offensive tokens enter the Warp. If defense loses, defending tokens enter the Warp and the planet’s former bases disappear.</p></div><div><Handshake/><h3>Compromise vs. Compromise</h3><p>The main players make a deal. In this version, a successful deal exchanges one legal foreign base. If they cannot agree or complete it, each main player loses three tokens to the Warp.</p></div><div><Shield/><h3>Attack vs. Compromise</h3><p>The Attack side wins automatically. The compromising player receives one random card from the winner for each token they lost, limited by the winner’s hand. This reward is called consolation.</p></div><div><Sparkles/><h3>Allies</h3><p>Offensive allies who win establish a base with their committed tokens. Defensive allies who win recover one token from the Warp or draw one card for each token they committed. Losing allied tokens go to the Warp.</p></div></div></section>
    <section id="cards"><p className="eyebrow">THE COSMIC DECK</p><h2>Know what you are holding.</h2><div className="card-rules"><div className="mini-card attack">12</div><div><h3>Attack</h3><p>Add the printed value to your side’s strength. Both main players must play a challenge card.</p></div><div className="mini-card compromise">C</div><div><h3>Compromise</h3><p>Creates a deal against another Compromise or consolation when played against an Attack.</p></div><div className="mini-card edict">✦</div><div><h3>Edict</h3><p>Cosmic Zap cancels a power for the current challenge. Force Field dismisses all allies. Mobius Tubes returns Warp tokens to their owners.</p></div><div className="mini-card kicker">×2</div><div><h3>Kicker</h3><p>Played in the tactics window to multiply your challenge card. A ×0 Kicker can turn an imposing card into nothing.</p></div><div className="mini-card flare">★</div><div><h3>Flare</h3><p>A Flare has a Wild effect for most players and a stronger Super effect for its matching alien. This edition currently includes Clone and Macron Flares.</p></div></div></section>
    <section id="powers"><p className="eyebrow">ALIEN POWERS</p><h2>The rule you alone may break.</h2><p>Your alien card changes a fundamental rule. Select it during play to open and read the full card. A power normally stays active while you hold bases on at least three of your five home planets.</p><div className="alien-rules">{aliens.map(([name,title,text],i)=><div key={name} style={{'--alien-index':i} as React.CSSProperties}><span/><small>ALIEN POWER</small><h3>{name}</h3><b>{title}</b><p>{text}</p></div>)}</div><div className="rule-warning"><b>Power loss</b><p>If you fall below three home bases, your power switches off. Reclaim enough home planets to restore it. Cosmic Zap and certain Moons can also suspend a power.</p></div></section>
    <section id="expansions"><p className="eyebrow">OPTIONAL EON MODULES</p><h2>Add the strange stuff.</h2><div className="expansion-list"><div><Coins/><h3>Lucre</h3><p>Begin with four. Gain one on the first challenge of your turn. Spend it during Regroup to recover extra tokens or buy cards, and commit it to strengthen your side in combat.</p></div><div><Orbit/><h3>Moons</h3><p>Each system has two. A Moon reveals its power when occupied and usually does not count toward victory. Moon challenges use no allies. Effects range from combat bonuses to Warp recovery and power disruption.</p></div><div><Sparkles/><h3>Flares</h3><p>Special cards tied to alien powers. Wild and Super effects bend launch limits, consolation, card use, and other rules.</p></div><div><Swords/><h3>Kickers</h3><p>Secret multipliers that make card reveals less predictable. They are played before the main challenge card.</p></div></div></section>
    <section id="solo"><p className="eyebrow">THIS DIGITAL TABLE</p><h2>What the computer handles for you.</h2><ul><li>Three rivals select targets, alliances, cards, and deals automatically.</li><li>Token sources and return destinations are chosen to preserve foreign bases and active powers when possible.</li><li>The game tracks bases, power status, rewards, the Warp, Lucre, and victory automatically.</li><li>Your expedition saves on this device after every move.</li><li>Deals currently exchange one base each. Flares apply automatically when their timing is relevant.</li><li>The current roster has eight powers: Clone, Macron, Virus, Zombie, Anti-Matter, Pacifist, Warpish, and Mutant.</li></ul></section>
  </article>
  <footer className="rules-footer"><div><b>READY TO BREAK THE RULES?</b><span>Your alien power is waiting.</span></div><a href="/">Return to the galaxy <ArrowLeft/></a></footer>
  </main>}
