'use client';
/* oxlint-disable next/no-html-link-for-pages -- simple internal links work in the Sites runtime */

import { useEffect, useState, type CSSProperties } from 'react';
import { ArrowRight, BookOpen, Coins, Eye, Orbit, RotateCcw, Shield, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ALIENS, FLARES, MOONS, applyAction, cardLabel, chooseBotAction, decision, deserialize, foreignBases, homeBases, launchLimit, newGame, powerActive, serialize, targetName, type Alien, type Card, type Game, type Planet, type Settings } from '@/lib/game';

const SAVE = 'cosmic-encounters-eon-v1';
const defaults: Settings = { alien:'Clone', flares:true, moons:true, lucre:true, kickers:true, difficulty:'standard' };
const phases = ['Regroup','Destiny','Launch','Alliance','Planning','Reveal'];
const alienArt: Alien[] = ['Clone','Macron','Virus','Zombie'];
const cardArt = (kind:Card['kind']) => ({attack:[0,0],compromise:[50,0],flare:[100,0],edict:[50,100],kicker:[0,100]}[kind]);
const phaseNumber = (g:Game) => ({regroup:0,destiny:1,launch:2,inviteO:3,inviteD:3,alliance:3,tactics:4,planning:4,reveal:5,deal:5,resolution:5,gameover:5})[g.phase];

export default function Home() {
  const [game,setGame] = useState(() => newGame(defaults));
  const [settings,setSettings] = useState(defaults);
  const [started,setStarted] = useState(false);
  const [ready,setReady] = useState(false);
  const [paused,setPaused] = useState(false);
  const [guide,setGuide] = useState(false);
  const [restart,setRestart] = useState(false);
  const [picked,setPicked] = useState('');
  const [error,setError] = useState('');
  const [inspected,setInspected] = useState<Card|null>(null);
  const [powerOpen,setPowerOpen] = useState(false);
  const d=decision(game), e=game.encounter, human=started&&d.player===0;
  const target=game.planets.find(x=>x.id===e.target);

  /* oxlint-disable react/react-compiler -- one-time hydration from device storage */
  useEffect(()=>{try{const raw=localStorage.getItem(SAVE);if(raw){const saved=deserialize(raw);setGame(saved);setSettings(saved.settings);setStarted(true)}}catch{setError('The saved expedition could not be loaded.')}setReady(true)},[]);
  /* oxlint-enable react/react-compiler */
  useEffect(()=>{if(started&&ready)localStorage.setItem(SAVE,serialize(game))},[game,started,ready]);
  useEffect(()=>{if(!started||paused||guide||restart||human||game.phase==='gameover')return;const timer=setTimeout(()=>{try{setGame(g=>applyAction(g,chooseBotAction(g)))}catch{setError('A computer move could not be resolved.');setPaused(true)}},480);return()=>clearTimeout(timer)},[game,started,paused,guide,restart,human]);
  const act=(id:string)=>{try{setGame(g=>applyAction(g,id));setPicked('');setError('')}catch(err){setError(err instanceof Error?err.message:'That move is unavailable.')}};
  const begin=()=>{setGame(newGame(settings,crypto.getRandomValues(new Uint32Array(1))[0]));setStarted(true);setRestart(false);setPaused(false);setPicked('');setError('')};
  const option=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(s=>({...s,[key]:value}));
  const powerCard=(alien:Alien,compact=false)=>{const art=alienArt.indexOf(alien);return <button type="button" className={`alien-card ${compact?'compact':''}`} style={{'--ax':`${(art%2)*100}%`,'--ay':`${Math.floor(art/2)*100}%`} as CSSProperties} onClick={()=>setPowerOpen(true)} aria-label={`Inspect ${alien} alien power card`}><span className="alien-portrait"/><span className="alien-copy"><small>ALIEN POWER</small><b>{alien}</b><em>{ALIENS[alien].title}</em>{!compact&&<p>{ALIENS[alien].description}</p>}<i><Eye/> Inspect card</i></span></button>};
  const setup=<div className="setup">
    <label htmlFor="alien">Your alien</label><Select value={settings.alien} onValueChange={v=>v&&option('alien',v as Alien)}><SelectTrigger id="alien" className="select"><SelectValue/></SelectTrigger><SelectContent>{Object.keys(ALIENS).map(a=><SelectItem key={a} value={a}>{a} · {ALIENS[a as Alien].title}</SelectItem>)}</SelectContent></Select>
    {powerCard(settings.alien,true)}<p className="form-heading">Expansion modules</p>
    {(['flares','moons','lucre','kickers'] as const).map(key=><label className="check" key={key}><Checkbox checked={settings[key]} onCheckedChange={v=>option(key,!!v)}/><span>{key[0].toUpperCase()+key.slice(1)}</span><small>{({flares:'2 curated cards',moons:'12 effects',lucre:'Eon economy',kickers:'Multipliers'})[key]}</small></label>)}
    <label htmlFor="difficulty">Computer rivals</label><Select value={settings.difficulty} onValueChange={v=>v&&option('difficulty',v as Settings['difficulty'])}><SelectTrigger id="difficulty" className="select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="standard">Standard · strategic</SelectItem><SelectItem value="relaxed">Relaxed · unpredictable</SelectItem></SelectContent></Select>
    <Button className="gold full" onClick={begin}>Begin expedition <ArrowRight size={17}/></Button><small>Four aliens. One human. Three rivals. Saved on this device.</small>
  </div>;

  const planet=(x:Planet)=>{const legal=human&&game.phase==='launch'&&d.actions.some(a=>a.target===x.id);const known=!x.moon||x.revealed||x.home===0;const art=(x.home*5+x.index+(x.moon?2:0))%6;return <button key={x.id} style={{'--px':`${(art%3)*50}%`,'--py':`${Math.floor(art/3)*100}%`} as CSSProperties} className={`planet ${x.moon?'moon':''} ${legal?'legal':''} ${picked===x.id?'picked':''} ${e.target===x.id?'aimed':''}`} disabled={!legal} onClick={()=>legal&&setPicked(x.id)} title={x.moon&&known?`${MOONS[x.moon].name}: ${MOONS[x.moon].description}`:x.moon?'Uncharted moon':`Planet ${x.index+1}`} aria-label={`${x.moon?(known?MOONS[x.moon].name:'Uncharted moon'):`Planet ${x.index+1}`}; ${x.ships.map((n,p)=>n?`${game.players[p].name} ${n}`:'').filter(Boolean).join(', ')}`}><span className="planet-id">{x.moon?'☾':x.index+1}</span><span className="tokens">{x.ships.map((n,p)=>n>0&&<i key={p} style={{'--token':game.players[p].color} as CSSProperties}>{n}</i>)}</span></button>};
  const card=(c:Card)=>{const play=human&&d.actions.find(a=>a.kind==='card'&&a.cardId===c.id);const art=cardArt(c.kind);return <button style={{'--cx':`${art[0]}%`,'--cy':`${art[1]}%`} as CSSProperties} className={`card ${c.kind} ${play?'playable':''}`} key={c.id} onClick={()=>setInspected(c)}><small>{c.kind.toUpperCase()}</small><strong>{c.kind==='attack'?c.value:c.kind==='compromise'?'C':c.kind==='kicker'?`×${c.value}`:<Sparkles/>}</strong><b>{cardLabel(c)}</b><span>{c.kind==='attack'?'Challenge card':c.kind==='compromise'?'Make a deal':c.kind==='flare'?'Alien flare':'Cosmic effect'}</span><i><Eye/> Turn over</i></button>};
  const launch=d.actions.filter(a=>a.kind==='launch'&&a.target===picked);

  return <main className="cosmos">
    <header className="masthead"><div><p className="eyebrow">THE EON YEARS · 1977—1983</p><h1>COSMIC <span>ENCOUNTERS</span></h1></div><nav><span>SOLO EXPEDITION</span><a className="nav-link" href="/rules"><BookOpen/> Complete rules</a><Button variant="ghost" onClick={()=>setGuide(true)}>Quick guide</Button>{started&&<Button variant="ghost" onClick={()=>setRestart(true)}><RotateCcw/> New game</Button>}</nav></header>
    <div className="topline"><span>● {started?'EXPEDITION IN PROGRESS':'YOUR TABLE IS READY'} <i>/ Eon adaptation · playable alpha</i></span><i>{started?`Turn ${game.turn} · Challenge ${game.challenge}`:'First to five foreign bases'}</i></div>{error&&<div role="alert" className="error">{error}</div>}
    <div className="layout"><section><div className="board-title"><div><p className="eyebrow">THE GALAXY</p><h2>{started?`${game.players[game.active].name==='You'?'Your':game.players[game.active].name+'’s'} challenge`:'Make yourself at home. Everywhere.'}</h2></div><strong>5 <small>BASES<br/>TO WIN</small></strong></div>
      <div className="galaxy">{[1,2,0,3].map(p=>{const player=game.players[p];const art=alienArt.indexOf(player.alien);return <section className={`system ${game.active===p&&started?'active':''}`} key={p} style={{'--player':player.color} as CSSProperties}><header><span className="seal" style={{'--ax':`${(art%2)*100}%`,'--ay':`${Math.floor(art/2)*100}%`} as CSSProperties}><i>{player.alien.slice(0,2).toUpperCase()}</i></span><div><h3>{player.alien}{p===0&&<small> YOU</small>}</h3><p>{powerActive(game,p)?ALIENS[player.alien].title:'Power inactive'} · {player.hand.length} cards</p></div><strong>{foreignBases(game,p)}<small>/5</small></strong></header><div className="planets">{game.planets.filter(x=>x.home===p&&!x.moon).map(planet)}</div><footer><span><Shield/> {homeBases(game,p)} home</span>{game.settings.lucre&&<span><Coins/> {player.lucre} Lucre</span>}<span className="moons">{game.planets.filter(x=>x.home===p&&x.moon).map(planet)}</span></footer></section>})}<div className="warp"><div><Orbit/><b>THE WARP</b><small>Lost, never forgotten.</small></div><span>{game.players.map(p=><i key={p.id} style={{color:p.color}}>● {p.warp}</i>)}</span></div></div>
      {started&&target&&<div className="cone"><ArrowRight/> <b>{game.players[game.active].name}</b> → {targetName(game,target)} <i>{e.ships.reduce((a,b)=>a+b,0)} tokens in the cone</i></div>}<div className="caption"><span>Colored discs show token counts.</span><span>{started?'✓ Saved on this device':'A personal tribute to the original game'}</span></div>
    </section><aside className="panel">{!started?<><p className="eyebrow">BEGIN A NEW EXPEDITION</p><h2>Your rules.<br/>Their problem.</h2><p>Choose your alien. Forge alliances with three computer rivals. Claim your corner of the cosmos.</p>{setup}</>:<><div className="panel-head"><p className="eyebrow">ENCOUNTER CONTROL</p><Button variant="ghost" onClick={()=>setPaused(x=>!x)}>{paused?'Resume':'Pause'}</Button></div><div className="phases">{phases.map((x,i)=><span className={i===phaseNumber(game)?'now':i<phaseNumber(game)?'done':''} key={x}>{i+1}</span>)}</div>
      {game.phase==='gameover'?<div className="victory"><Sparkles/><p className="eyebrow">THE GALAXY IS SETTLED</p><h2>{game.winners.includes(0)?'You made it.':`${game.players[game.winners[0]].name} prevails.`}</h2><p>{game.winners.map(p=>game.players[p].name).join(' and ')} {game.winners.length>1?'share victory.':'claims victory.'}</p><Button className="gold full" onClick={()=>setRestart(true)}>Another universe <ArrowRight/></Button></div>:<><b className="turn">{paused?'COMPUTERS PAUSED':human?'YOUR DECISION':`${game.players[d.player].name.toUpperCase()} IS DECIDING`}</b><h2>{d.title}</h2><p>{d.help}</p>
        {human&&game.phase==='launch'?<div><p className="instruction">1. Select a glowing destination on the board.</p>{picked&&<><p className="instruction">2. Commit tokens · maximum {launchLimit(game,0)}</p><div className="numbers">{launch.map(a=><Button key={a.id} onClick={()=>act(a.id)}>{a.count}</Button>)}</div></>}</div>:human&&game.phase==='planning'?<div className="prompt"><ArrowRight/> Play a glowing card from your hand.</div>:human?<div className="actions">{d.actions.map((a,i)=><Button variant={i?'outline':'default'} key={a.id} onClick={()=>act(a.id)}><span>{a.label}{a.detail&&<small>{a.detail}</small>}</span><ArrowRight/></Button>)}</div>:<div className="thinking"><span>● ● ●</span><p>{paused?'Resume to continue.':'Considering the possibilities…'}</p></div>}
      </>}<div className={`power-card-wrap ${powerActive(game,0)?'':'inactive'}`}>{powerCard(game.players[0].alien,true)}{!powerActive(game,0)&&<p>Your power is inactive. Reclaim three home bases.</p>}</div></>}</aside></div>
    {started&&<section className="hand"><div className="section-title"><div><p className="eyebrow">YOUR HAND</p><h2>{game.phase==='planning'&&human?'Your next move changes everything.':'A few secrets worth keeping.'}</h2></div><span>{game.players[0].hand.length} cards · private</span></div><div className="cards">{game.players[0].hand.map(card)}</div>{game.players[0].hand.filter(c=>c.kind==='flare').map(c=><p className="flare-note" key={c.id}><Sparkles/> <b>{c.name} Flare:</b> {game.players[0].alien===c.name&&powerActive(game,0)?FLARES[c.name].super:FLARES[c.name].wild}</p>)}</section>}
    {started&&<section className="log"><div className="section-title"><p className="eyebrow">TRANSMISSIONS</p><span>Latest first</span></div><ol>{game.log.slice(-10).reverse().map((x,i)=><li key={`${game.log.length-i}-${x}`}><b>{String(game.log.length-i).padStart(2,'0')}</b>{x}</li>)}</ol></section>}
    <div className="page-footer"><b>COSMIC ENCOUNTERS <i>/ Eon-era adaptation</i></b><a href="/rules">Read the complete rules <ArrowRight/></a></div>
    <Dialog open={restart} onOpenChange={setRestart}><DialogContent className="dialog"><DialogHeader><DialogTitle>Begin another expedition</DialogTitle><DialogDescription>This replaces the expedition saved on this device.</DialogDescription></DialogHeader>{setup}</DialogContent></Dialog>
    <Dialog open={!!inspected} onOpenChange={open=>!open&&setInspected(null)}><DialogContent className="dialog card-dialog">{inspected&&<><div className={`big-card ${inspected.kind}`}><small>{inspected.kind.toUpperCase()}</small><strong>{inspected.kind==='attack'?inspected.value:inspected.kind==='compromise'?'C':inspected.kind==='kicker'?`×${inspected.value}`:<Sparkles/>}</strong><h2>{cardLabel(inspected)}</h2><div className="card-rule">{inspected.kind==='attack'?'Add this number to the strength of the tokens on your side.':inspected.kind==='compromise'?'If both sides reveal Compromise, make a deal. Against an Attack, receive consolation cards.':inspected.kind==='flare'?`${FLARES[inspected.name!].wild} ${game.players[0].alien===inspected.name?`Super: ${FLARES[inspected.name!].super}`:''}`:inspected.kind==='kicker'?'Multiply your side’s challenge card before totals are compared.':inspected.name==='Cosmic Zap'?'Temporarily cancel an alien power for this encounter.':'Return every token from the Warp to its owner’s bases.'}</div><footer>THE EON YEARS · COSMIC ENCOUNTERS</footer></div>{human&&d.actions.find(a=>a.kind==='card'&&a.cardId===inspected.id)&&<Button className="gold full" onClick={()=>{const move=d.actions.find(a=>a.kind==='card'&&a.cardId===inspected.id);if(move){setInspected(null);act(move.id)}}}>Play this card <ArrowRight/></Button>}</>}</DialogContent></Dialog>
    <Dialog open={powerOpen} onOpenChange={setPowerOpen}><DialogContent className="dialog power-dialog">{powerCard(started?game.players[0].alien:settings.alien)}<div className="power-lore"><p className="eyebrow">HOW TO USE THIS POWER</p><p>{ALIENS[started?game.players[0].alien:settings.alien].hint}</p>{started&&!powerActive(game,0)&&<b>POWER INACTIVE · Reclaim three home bases to restore it.</b>}</div></DialogContent></Dialog>
    <Dialog open={guide} onOpenChange={setGuide}><DialogContent className="dialog guide"><DialogHeader><DialogTitle>Field guide to the cosmos</DialogTitle><DialogDescription>A playable Eon-era adaptation with a growing rules library.</DialogDescription></DialogHeader><h3>Five foreign bases. Any route there.</h3><p>A base is one or more of your tokens on a planet. Reach five planets outside your home system to win. Allies can win together. Ordinary moons don’t count.</p><h3>The encounter</h3><p>Regroup, turn destiny, launch, invite allies, then choose a challenge card. Attack totals combine cards, token strength, alien effects and Lucre. Defense wins ties. Compromise enables deals or consolation.</p><h3>Playable today</h3><p>Clone, Macron, Virus and Zombie; the original attack distribution and Compromises; Mobius Tubes, Cosmic Zap and Force Field; Clone and Macron Flares; twelve moon effects; Lucre and Kickers.</p><h3>Alpha adaptations</h3><ul><li>Token movement is automatic and tries to preserve bases.</li><li>Deals currently exchange one base each.</li><li>Flares apply automatically when relevant.</li><li>Edicts use one pre-card tactics window.</li><li>Reverse Cone, Praw, alternate hexes and the remaining expansion library are planned.</li></ul><h3>Sources</h3><p>This independent personal adaptation uses Eon’s 1983 consolidated rules. It is not an official release.</p><div className="links"><a href="https://daveola.com/CosmicEncounter/Rules/Eon.Rules.pdf" target="_blank">Eon rules ↗</a><a href="https://daveola.com/CosmicEncounter/Rules/Eon_Appendix.pdf" target="_blank">Eon appendix ↗</a><a href="https://github.com/fintechjunkie/cosmic-encounters" target="_blank">Project plan ↗</a></div></DialogContent></Dialog>
  </main>;
}
